"""Shared timing and API limits (aligned with Material/Desktop-Agent + web tracker)."""

SESSION_POLL_SEC = 5
APP_LOG_INTERVAL_SEC = 15
FIRST_SCREENSHOT_DELAY_SEC = 20

SCREENSHOT_MIN_DELAY_SEC = 90
SCREENSHOT_MAX_DELAY_SEC = 210

ACTIVITY_WINDOW_MS = 60_000
ACTIVITY_SATURATION_EVENTS = 120
ACTIVITY_MIN_SCORE = 5

TOKEN_REFRESH_BUFFER_MS = 120_000
MIN_TOKEN_LENGTH = 20

HTTP_TIMEOUT_SEC = 15
EVENT_POST_TIMEOUT_SEC = 30
URL_SCRIPT_TIMEOUT_SEC = 8

MAX_SCREENSHOT_WIDTH = 1280
JPEG_QUALITY = 72
MAX_APP_NAME_LEN = 200
MAX_PAGE_TITLE_LEN = 300
MAX_URL_LEN = 2000

EVENT_SOURCE = "agent"
REGISTER_SOURCE = "python"

AUTH_PATH = "/auth"
HEALTH_PATH = "/health"
