export const memberSchemas = [
  {
    key: "members",
    collection: "members",
    fields: {
      id: "uuid",
      first_name: "string",
      last_name: "string",
      work_email: "string",
      personal_email: "string",
      employee_id: "string",
      ip_address: "string",
      status: "string",
      role_id: "uuid",
      hierarchy_status: "string",
      hierarchy_entitlements: "object",
      privileges: "object",
      independent_hierarchy: "boolean",
      hierarchy_status_updated_at: "timestamp",
      date_added: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
      updated_at: "timestamp",
    },
    defaultOrderBy: "date_added",
  },
  {
    key: "roles",
    collection: "roles",
    fields: {
      id: "uuid",
      name: "string",
      description: "text",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "member-onboarding",
    collection: "member_onboarding",
    fields: {
      id: "uuid",
      member_id: "uuid",
      invite_id: "uuid",
      created_account: "boolean",
      created_account_at: "timestamp",
      downloaded_app: "boolean",
      downloaded_app_at: "timestamp",
      tracked_time: "boolean",
      tracked_time_at: "timestamp",
      last_reminder_sent_at: "timestamp",
      last_reminder_sent_by: "uuid",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
      updated_at: "timestamp",
    },
  },
  {
    key: "invites",
    collection: "invites",
    fields: {
      id: "uuid",
      email: "string",
      role_id: "uuid",
      invite_token: "string",
      invite_kind: "string",
      firebase_uid: "string",
      pay_rate: "decimal",
      weekly_limit: "string",
      currency: "string",
      status: "string",
      sent_at: "timestamp",
      accepted_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "invite-projects",
    collection: "invite_projects",
    fields: {
      id: "uuid",
      invite_id: "uuid",
      project_id: "uuid",
      created_by: "uuid",
    },
  },
];
