import { COLLECTIONS } from "../../../../lib/firestore/collections.js";

export const projectSchemas = [
  {
    key: "projects",
    collection: COLLECTIONS.projects,
    fields: {
      id: "uuid",
      name: "string",
      billable: "boolean",
      disable_activity: "boolean",
      allow_project_tracking: "boolean",
      disable_idle_time: "boolean",
      client_id: "uuid",
      managers_notes: "text",
      users_notes: "text",
      viewers_notes: "text",
      status: "string",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
      updated_at: "timestamp",
      archived_by: "uuid",
      archived_at: "timestamp",
    },
  },
  {
    key: "project-members",
    collection: "project_members",
    fields: {
      id: "uuid",
      project_id: "uuid",
      member_id: "uuid",
      project_role: "string",
      assigned_at: "timestamp",
      assigned_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "project-budgets",
    collection: "project_budgets",
    fields: {
      id: "uuid",
      project_id: "uuid",
      type: "string",
      based_on: "string",
      cost: "decimal",
      notify_project_members: "boolean",
      notify_at_pct: "decimal",
      who_to_notify: "string",
      stop_timers_when_reached: "boolean",
      stop_timers_at_pct: "decimal",
      resets: "string",
      start_date: "date",
      include_non_billable_time: "boolean",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "project-member-limits",
    collection: "project_member_limits",
    fields: {
      id: "uuid",
      project_id: "uuid",
      member_id: "uuid",
      type: "string",
      based_on: "string",
      cost: "decimal",
      resets: "string",
      start_date: "date",
      notify_at_pct: "decimal",
      notify_project_members: "boolean",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
];
