export const employmentSchemas = [
  {
    key: "job-titles",
    collection: "job_titles",
    fields: {
      id: "uuid",
      name: "string",
      list_ranking: "string",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "departments",
    collection: "departments",
    fields: {
      id: "uuid",
      name: "string",
      list_ranking: "string",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "job-types",
    collection: "job_types",
    fields: {
      id: "uuid",
      name: "string",
      list_ranking: "string",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "tax-types",
    collection: "tax_types",
    fields: {
      id: "uuid",
      name: "string",
      list_ranking: "string",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "employment",
    collection: "employment",
    fields: {
      id: "uuid",
      member_id: "uuid",
      job_title_id: "uuid",
      department_id: "uuid",
      job_type_id: "uuid",
      tax_type_id: "uuid",
      work_address: "string",
      mailing_address: "boolean",
      employment_type: "string",
      employed_through: "string",
      workplace_model: "string",
      pct_in_office: "decimal",
      pct_remote: "decimal",
      tax_info: "string",
      account_code: "string",
      currency: "string",
      start_date: "date",
      end_date: "date",
      termination_reason: "string",
      employment_comments: "text",
      created_by: "uuid",
      updated_by: "uuid",
      updated_at: "timestamp",
    },
  },
  {
    key: "pay-rates",
    collection: "pay_rates",
    fields: {
      id: "uuid",
      member_id: "uuid",
      type: "string",
      rate: "decimal",
      currency: "string",
      pay_period: "string",
      require_timesheet_approval: "boolean",
      effective_date: "date",
      status: "string",
      note: "text",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "time-settings",
    collection: "time_settings",
    fields: {
      id: "uuid",
      member_id: "uuid",
      able_to_track_time: "boolean",
      keep_idle_time: "string",
      idle_timeout: "string",
      modify_time: "string",
      require_approval: "boolean",
      work_days: "array",
      disable_tracking_specific_days: "boolean",
      use_shifts_for_limits: "boolean",
      updated_by: "uuid",
    },
  },
  {
    key: "limits",
    collection: "limits",
    fields: {
      id: "uuid",
      weekly: "decimal",
      daily: "decimal",
      updated_by: "uuid",
      updated_at: "timestamp",
    },
  },
];
