export const activitySchemas = [
  {
    key: "activity-sessions",
    collection: "activity_sessions",
    fields: {
      id: "uuid",
      member_id: "uuid",
      status: "string",
      started_at: "timestamp",
      ended_at: "timestamp",
      active_seconds: "int",
      idle_seconds: "int",
      task_id: "uuid",
      updated_at: "timestamp",
    },
  },
  {
    key: "activity-screenshots",
    collection: "activity_screenshots",
    fields: {
      id: "uuid",
      member_id: "uuid",
      session_id: "uuid",
      image_data: "text",
      app_name: "string",
      page_title: "string",
      activity_level: "int",
      captured_at: "timestamp",
    },
  },
  {
    key: "activity-app-logs",
    collection: "activity_app_logs",
    fields: {
      id: "uuid",
      member_id: "uuid",
      session_id: "uuid",
      app_name: "string",
      started_at: "timestamp",
      ended_at: "timestamp",
      duration_seconds: "int",
    },
  },
  {
    key: "activity-url-logs",
    collection: "activity_url_logs",
    fields: {
      id: "uuid",
      member_id: "uuid",
      session_id: "uuid",
      url: "string",
      domain: "string",
      page_title: "string",
      visited_at: "timestamp",
      duration_seconds: "int",
    },
  },
  {
    key: "activity-alert-log",
    collection: "activity_alert_log",
    fields: {
      id: "uuid",
      subject_member_id: "uuid",
      alert_type: "string",
      recipient_ids: "array",
      sent_at: "timestamp",
    },
  },
];
