export const taskSchemas = [
  {
    key: "tasks",
    collection: "tasks",
    fields: {
      id: "uuid",
      project_id: "uuid",
      team_id: "uuid",
      title: "string",
      description: "text",
      status: "string",
      priority: "string",
      order_index: "int",
      duration_hours_per_day: "float",
      duration_days: "int",
      working_days: "int",
      overtime_hours_per_day: "float",
      assigned_to: "uuid",
      start_date: "timestamp",
      due_date: "timestamp",
      review_state: "string",
      reviewed_by: "uuid",
      reviewed_at: "timestamp",
      created_at: "timestamp",
      updated_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "task-subtasks",
    collection: "task_subtasks",
    fields: {
      id: "uuid",
      task_id: "uuid",
      title: "string",
      completed: "boolean",
      order_index: "int",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "task-comments",
    collection: "task_comments",
    fields: {
      id: "uuid",
      task_id: "uuid",
      body: "text",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "task-attachments",
    collection: "task_attachments",
    fields: {
      id: "uuid",
      task_id: "uuid",
      file_url: "string",
      file_name: "string",
      uploaded_at: "timestamp",
      uploaded_by: "uuid",
    },
  },
  {
    key: "task-assignments",
    collection: "task_assignments",
    fields: {
      id: "uuid",
      task_id: "uuid",
      user_id: "uuid",
      project_id: "uuid",
      status: "string",
      expected_seconds: "int",
      required: "boolean",
      review_state: "string",
      reviewed_by: "uuid",
      reviewed_at: "timestamp",
      review_notes: "text",
      entered_review_at: "timestamp",
      created_at: "timestamp",
      updated_at: "timestamp",
    },
  },
  {
    key: "task-hours",
    collection: "task_hours",
    fields: {
      id: "uuid",
      task_id: "uuid",
      user_id: "uuid",
      hours_spent: "float",
      status: "string",
      submitted_at: "timestamp",
      created_at: "timestamp",
      updated_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "task-time-tracking",
    collection: "task_time_tracking",
    fields: {
      id: "uuid",
      task_id: "uuid",
      user_id: "uuid",
      project_id: "uuid",
      active_seconds: "int",
      idle_seconds: "int",
      started_at: "timestamp",
      last_activity_at: "timestamp",
      session_id: "string",
      review_notes: "text",
      created_at: "timestamp",
      updated_at: "timestamp",
    },
  },
];
