export const taskSchemas = [
  {
    key: "tasks",
    collection: "tasks",
    fields: {
      id: "uuid",
      project_id: "uuid",
      team_id: "uuid",
      title: "string",
      description: "text",
      status: "string",
      priority: "string",
      order_index: "int",
      duration_hours_per_day: "float",
      duration_days: "int",
      working_days: "int",
      overtime_hours_per_day: "float",
      rolling_hour_cap: "boolean",
      assigned_to: "uuid",
      start_date: "timestamp",
      due_date: "timestamp",
      review_state: "string",
      reviewed_by: "uuid",
      reviewed_at: "timestamp",
      created_at: "timestamp",
      updated_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "task-subtasks",
    collection: "tasks",
    subcollection: "subtasks",
    parentIdField: "task_id",
    fields: {
      id: "uuid",
      task_id: "uuid",
      title: "string",
      completed: "boolean",
      order_index: "int",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "task-comments",
    collection: "tasks",
    subcollection: "comments",
    parentIdField: "task_id",
    fields: {
      id: "uuid",
      task_id: "uuid",
      body: "text",
      created_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  {
    key: "task-attachments",
    collection: "tasks",
    subcollection: "attachments",
    parentIdField: "task_id",
    fields: {
      id: "uuid",
      task_id: "uuid",
      file_url: "string",
      file_name: "string",
      uploaded_at: "timestamp",
      uploaded_by: "uuid",
    },
  },
  {
    key: "task-assignments",
    collection: "task_assignments",
    fields: {
      id: "uuid",
      task_id: "uuid",
      member_id: "uuid",
      project_id: "uuid",
      status: "string",
      expected_seconds: "int",
      required: "boolean",
      review_state: "string",
      reviewed_by: "uuid",
      reviewed_at: "timestamp",
      review_notes: "text",
      entered_review_at: "timestamp",
      created_at: "timestamp",
      updated_at: "timestamp",
    },
  },
  {
    key: "task-hours",
    collection: "tasks",
    subcollection: "hours",
    parentIdField: "task_id",
    fields: {
      id: "uuid",
      task_id: "uuid",
      user_id: "uuid",
      hours_spent: "float",
      status: "string",
      submitted_at: "timestamp",
      created_at: "timestamp",
      updated_at: "timestamp",
      created_by: "uuid",
      updated_by: "uuid",
    },
  },
  // task-time-tracking removed (implementation.md legacy cleanup) - this
  // Firestore subcollection catalog entry backed a generic dispatcher path
  // (/api/tasks/:id/time_tracking, underscore) that no real caller ever hit;
  // the actual feature is served entirely by task-time-tracking.js's own
  // dedicated /api/tasks/:id/time-tracking (hyphen) route against Postgres
  // task_member_progress since Phase 2. Leaving this registered meant a
  // reachable-but-dead endpoint could silently write into an orphaned
  // Firestore collection nothing reads back from.
];
