import type { MetadataRoute } from "next"

const baseUrl = "https://virtualtracker.com"

const routes = [
  "/",
  "/features",
  "/pricing",
  "/solutions",
  "/about",
  "/demo",
  "/contact",
  "/resources",
  "/hour-logging",
  "/output-visibility",
  "/workforce-signals",
  "/pay-invoicing",
  "/connected-apps",
  "/smart-timesheets",
  "/team-visibility",
  "/custom-reports",
  "/client-invoicing",
  "/about-us",
  "/guiding-principles",
  "/reviews",
  "/press",
  "/partners",
  "/status",
  "/product-roadmap",
  "/careers",
  "/download-virtual-tracker",
  "/mac-time-tracker",
  "/linux-time-tracker",
  "/windows-time-tracker",
  "/web-time-tracker",
  "/help-center",
  "/sign-in",
  "/contact-us",
  "/resource-hub",
  "/time-tracking-resources",
  "/roi-calculator",
  "/buy-in-guide",
  "/faq",
  "/customer-stories",
  "/blog",
  "/toggl",
  "/clockify",
  "/insightful",
  "/apploye",
  "/activtrak",
  "/time-doctor",
  "/desktime",
  "/see-all-comparisons",
]

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "/" ? "weekly" : "monthly",
    priority: route === "/" ? 1 : 0.8,
  }))
}
