export type {
  ANGLE_instanced_arrays,
  EXT_blend_minmax,
  EXT_texture_filter_anisotropic,
  OES_element_index_uint,
  OES_standard_derivatives,
  OES_texture_float,
  OES_texture_half_float,
  OES_vertex_array_object,
  WEBGL_compressed_texture_s3tc,
  WEBGL_depth_texture,
  WEBGL_draw_buffers,
  WEBGL_lose_context,
  WebGLExtensionMap,
} from '../global/global';